'@Interface

Property Get ActiveCell() As Range
End Property

Property Get ActiveChart() As Chart
End Property

Property Get ActiveEncryptionSession() As Long
End Property

Property Get ActivePrinter() As String
End Property
Property Let ActivePrinter() As String
End Property

Property Get ActiveProtectedViewWindow() As ProtectedViewWindow
End Property

Property Get ActiveSheet() As Worksheet
End Property

Property Get ActiveWindow() As Window
End Property

Property Get ActiveWorkbook() As Workbook
End Property

Property Get AddIns() As AddIns
End Property

Property Get AddIns2() As AddIns2
End Property

Property Get AlertBeforeOverwriting() As Boolean
End Property
Property Let AlertBeforeOverwriting() As Boolean
End Property

Property Get AltStartupPath() As String
End Property
Property Let AltStartupPath() As String
End Property

Property Get AlwaysUseClearType() As Boolean
End Property
Property Let AlwaysUseClearType() As Boolean
End Property

Property Get Application() As Application
End Property

Property Get ArbitraryXMLSupportAvailable() As Boolean
End Property

Property Get AskToUpdateLinks() As Boolean
End Property
Property Let AskToUpdateLinks() As Boolean
End Property

Property Get Assistance() As IAssistance
End Property

Property Get AutoCorrect() As AutoCorrect
End Property

Property Get AutoFormatAsYouTypeReplaceHyperlinks() As Boolean
End Property
Property Let AutoFormatAsYouTypeReplaceHyperlinks() As Boolean
End Property

Property Get AutomationSecurity() As MsoAutomationSecurity
End Property
Property Let AutomationSecurity() As MsoAutomationSecurity
End Property

Property Get AutoPercentEntry() As Boolean
End Property
Property Let AutoPercentEntry() As Boolean
End Property

Property Get AutoRecover() As AutoRecover
End Property

Property Get Build() As Long
End Property

Property Get CalculateBeforeSave() As Boolean
End Property
Property Let CalculateBeforeSave() As Boolean
End Property

Property Get Calculation() As XlCalculation
End Property
Property Let Calculation() As XlCalculation
End Property

Property Get CalculationInterruptKey() As XlCalculationInterruptKey
End Property
Property Let CalculationInterruptKey() As XlCalculationInterruptKey
End Property

Property Get CalculationState() As XlCalculationState
End Property

Property Get CalculationVersion() As Long
End Property

Property Get Caller(Optional Index)
End Property

Property Get CanPlaySounds() As Boolean
End Property

Property Get CanRecordSounds() As Boolean
End Property

Property Get Caption() As String
End Property
Property Let Caption() As String
End Property

Property Get CellDragAndDrop() As Boolean
End Property
Property Let CellDragAndDrop() As Boolean
End Property

Property Get Cells() As Range
End Property

Property Get ChartDataPointTrack() As Boolean
End Property
Property Let ChartDataPointTrack() As Boolean
End Property

Property Get Charts() As Sheets
End Property

Property Get ClipboardFormats(Optional Index)
End Property

Property Get ClusterConnector() As String
End Property
Property Let ClusterConnector() As String
End Property

Property Get Columns() As Range
End Property

Property Get COMAddIns() As COMAddIns
End Property

Property Get CommandBars() As CommandBars
End Property

Property Get CommandUnderlines() As XlCommandUnderlines
End Property
Property Let CommandUnderlines() As XlCommandUnderlines
End Property

Property Get ConstrainNumeric() As Boolean
End Property
Property Let ConstrainNumeric() As Boolean
End Property

Property Get ControlCharacters() As Boolean
End Property
Property Let ControlCharacters() As Boolean
End Property

Property Get CopyObjectsWithCells() As Boolean
End Property
Property Let CopyObjectsWithCells() As Boolean
End Property

Property Get Creator() As XlCreator
End Property

Property Get Cursor() As XlMousePointer
End Property
Property Let Cursor() As XlMousePointer
End Property

Property Get CursorMovement() As Long
End Property
Property Let CursorMovement() As Long
End Property

Property Get CustomListCount() As Long
End Property

Property Get CutCopyMode() As XlCutCopyMode
End Property
Property Let CutCopyMode() As XlCutCopyMode
End Property

Property Get DataEntryMode() As Long
End Property
Property Let DataEntryMode() As Long
End Property

Property Get DDEAppReturnCode() As Long
End Property

Property Get DecimalSeparator() As String
End Property
Property Let DecimalSeparator() As String
End Property

Property Get DefaultFilePath() As String
End Property
Property Let DefaultFilePath() As String
End Property

Property Get DefaultSaveFormat() As XlFileFormat
End Property
Property Let DefaultSaveFormat() As XlFileFormat
End Property

Property Get DefaultSheetDirection() As Long
End Property
Property Let DefaultSheetDirection() As Long
End Property

Property Get DefaultWebOptions() As DefaultWebOptions
End Property

Property Get DeferAsyncQueries() As Boolean
End Property
Property Let DeferAsyncQueries() As Boolean
End Property

Property Get Dialogs() As Dialogs
End Property

Property Get DisplayAlerts() As Boolean
End Property
Property Let DisplayAlerts() As Boolean
End Property

Property Get DisplayClipboardWindow() As Boolean
End Property
Property Let DisplayClipboardWindow() As Boolean
End Property

Property Get DisplayCommentIndicator() As XlCommentDisplayMode
End Property
Property Let DisplayCommentIndicator() As XlCommentDisplayMode
End Property

Property Get DisplayDocumentActionTaskPane() As Boolean
End Property
Property Let DisplayDocumentActionTaskPane() As Boolean
End Property

Property Get DisplayDocumentInformationPanel() As Boolean
End Property
Property Let DisplayDocumentInformationPanel() As Boolean
End Property

Property Get DisplayExcel4Menus() As Boolean
End Property
Property Let DisplayExcel4Menus() As Boolean
End Property

Property Get DisplayFormulaAutoComplete() As Boolean
End Property
Property Let DisplayFormulaAutoComplete() As Boolean
End Property

Property Get DisplayFormulaBar() As Boolean
End Property
Property Let DisplayFormulaBar() As Boolean
End Property

Property Get DisplayFullScreen() As Boolean
End Property
Property Let DisplayFullScreen() As Boolean
End Property

Property Get DisplayFunctionToolTips() As Boolean
End Property
Property Let DisplayFunctionToolTips() As Boolean
End Property

Property Get DisplayInsertOptions() As Boolean
End Property
Property Let DisplayInsertOptions() As Boolean
End Property

Property Get DisplayNoteIndicator() As Boolean
End Property
Property Let DisplayNoteIndicator() As Boolean
End Property

Property Get DisplayPasteOptions() As Boolean
End Property
Property Let DisplayPasteOptions() As Boolean
End Property

Property Get DisplayRecentFiles() As Boolean
End Property
Property Let DisplayRecentFiles() As Boolean
End Property

Property Get DisplayScrollBars() As Boolean
End Property
Property Let DisplayScrollBars() As Boolean
End Property

Property Get DisplayStatusBar() As Boolean
End Property
Property Let DisplayStatusBar() As Boolean
End Property

Property Get EditDirectlyInCell() As Boolean
End Property
Property Let EditDirectlyInCell() As Boolean
End Property

Property Get EnableAnimations() As Boolean
End Property
Property Let EnableAnimations() As Boolean
End Property

Property Get EnableAutoComplete() As Boolean
End Property
Property Let EnableAutoComplete() As Boolean
End Property

Property Get EnableCancelKey() As XlEnableCancelKey
End Property
Property Let EnableCancelKey() As XlEnableCancelKey
End Property

Property Get EnableCheckFileExtensions() As Boolean
End Property
Property Let EnableCheckFileExtensions() As Boolean
End Property

Property Get EnableEvents() As Boolean
End Property
Property Let EnableEvents() As Boolean
End Property

Property Get EnableLargeOperationAlert() As Boolean
End Property
Property Let EnableLargeOperationAlert() As Boolean
End Property

Property Get EnableLivePreview() As Boolean
End Property
Property Let EnableLivePreview() As Boolean
End Property

Property Get EnableMacroAnimations() As Boolean
End Property
Property Let EnableMacroAnimations() As Boolean
End Property

Property Get EnableSound() As Boolean
End Property
Property Let EnableSound() As Boolean
End Property

Property Get ErrorCheckingOptions() As ErrorCheckingOptions
End Property

Property Get Excel4IntlMacroSheets() As Sheets
End Property

Property Get Excel4MacroSheets() As Sheets
End Property

Property Get ExtendList() As Boolean
End Property
Property Let ExtendList() As Boolean
End Property

Property Get FeatureInstall() As MsoFeatureInstall
End Property
Property Let FeatureInstall() As MsoFeatureInstall
End Property

Property Get FileConverters(Optional Index1, Optional Index2)
End Property

Property Get FileDialog(fileDialogType As MsoFileDialogType) As FileDialog
End Property

Property Get FileExportConverters() As FileExportConverters
End Property

Property Get FileValidation() As MsoFileValidationMode
End Property
Property Let SetFileValidation() As MsoFileValidationMode
End Property

Property Get FileValidationPivot() As XlFileValidationPivotMode
End Property
Property Let SetFileValidationPivot() As XlFileValidationPivotMode
End Property

Property Get FindFormat() As CellFormat
End Property
Property Let FindFormat() As CellFormat
End Property

Property Get FixedDecimal() As Boolean
End Property
Property Let FixedDecimal() As Boolean
End Property

Property Get FixedDecimalPlaces() As Long
End Property
Property Let FixedDecimalPlaces() As Long
End Property

Property Get FlashFill() As Boolean
End Property
Property Let FlashFill() As Boolean
End Property

Property Get FlashFillMode() As Boolean
End Property
Property Let FlashFillMode() As Boolean
End Property

Property Get FormulaBarHeight() As Long
End Property
Property Let FormulaBarHeight() As Long
End Property

Property Get GenerateGetPivotData() As Boolean
End Property
Property Let GenerateGetPivotData() As Boolean
End Property

Property Get GenerateTableRefs() As XlGenerateTableRefs
End Property
Property Let GenerateTableRefs() As XlGenerateTableRefs
End Property

Property Get Height() As Double
End Property
Property Let Height() As Double
End Property

Property Get HighQualityModeForGraphics() As Boolean
End Property
Property Let HighQualityModeForGraphics() As Boolean
End Property

Property Get Hinstance() As Long
End Property

Property Get HinstancePtr() As Variant
End Property

Property Get Hwnd() As Long
End Property

Property Get IgnoreRemoteRequests() As Boolean
End Property
Property Let IgnoreRemoteRequests() As Boolean
End Property

Property Get Interactive() As Boolean
End Property
Property Let Interactive() As Boolean
End Property

Property Get International(Optional Index)
End Property

Property Get IsSandboxed() As Boolean
End Property

Property Get Iteration() As Boolean
End Property
Property Let Iteration() As Boolean
End Property

Property Get LanguageSettings() As LanguageSettings
End Property

Property Get LargeOperationCellThousandCount() As Long
End Property
Property Let LargeOperationCellThousandCount() As Long
End Property

Property Get Left() As Double
End Property
Property Let Left() As Double
End Property

Property Get LibraryPath() As String
End Property

Property Get MailSession() As Variant
End Property

Property Get MailSystem() As XlMailSystem
End Property

Property Get MapPaperSize() As Boolean
End Property
Property Let MapPaperSize() As Boolean
End Property

Property Get MathCoprocessorAvailable() As Boolean
End Property

Property Get MaxChange() As Double
End Property
Property Let MaxChange() As Double
End Property

Property Get MaxIterations() As Long
End Property
Property Let MaxIterations() As Long
End Property

Property Get MeasurementUnit() As Long
End Property
Property Let MeasurementUnit() As Long
End Property

Property Get MergeInstances() As Boolean
End Property
Property Let MergeInstances() As Boolean
End Property

Property Get MouseAvailable() As Boolean
End Property

Property Get MoveAfterReturn() As Boolean
End Property
Property Let MoveAfterReturn() As Boolean
End Property

Property Get MoveAfterReturnDirection() As XlDirection
End Property
Property Let MoveAfterReturnDirection() As XlDirection
End Property

Property Get MultiThreadedCalculation() As MultiThreadedCalculation
End Property

Property Get Name() As String
End Property

Property Get Names() As Names
End Property

Property Get NetworkTemplatesPath() As String
End Property

Property Get NewWorkbook() As NewFile
End Property

Property Get ODBCErrors() As ODBCErrors
End Property

Property Get ODBCTimeout() As Long
End Property
Property Let ODBCTimeout() As Long
End Property

Property Get OLEDBErrors() As OLEDBErrors
End Property

Property Get OnWindow() As String
End Property
Property Let OnWindow() As String
End Property

Property Get OperatingSystem() As String
End Property

Property Get OrganizationName() As String
End Property

Property Get Parent() As Application
End Property

Property Get Path() As String
End Property

Property Get PathSeparator() As String
End Property

Property Get PivotTableSelection() As Boolean
End Property
Property Let PivotTableSelection() As Boolean
End Property

Property Get PreviousSelections(Optional Index)
End Property

Property Get PrintCommunication() As Boolean
End Property
Property Let PrintCommunication() As Boolean
End Property

Property Get ProductCode() As String
End Property

Property Get PromptForSummaryInfo() As Boolean
End Property
Property Let PromptForSummaryInfo() As Boolean
End Property

Property Get ProtectedViewWindows() As ProtectedViewWindows
End Property

Property Get QuickAnalysis() As QuickAnalysis
End Property

Property Get Range(Cell1, Optional Cell2) As Range
End Property

Property Get Ready() As Boolean
End Property

Property Get RecentFiles() As RecentFiles
End Property

Property Get RecordRelative() As Boolean
End Property

Property Get ReferenceStyle() As XlReferenceStyle
End Property
Property Let ReferenceStyle() As XlReferenceStyle
End Property

Property Get RegisteredFunctions(Optional Index1, Optional Index2)
End Property

Property Get ReplaceFormat() As CellFormat
End Property
Property Let ReplaceFormat() As CellFormat
End Property

Property Get RollZoom() As Boolean
End Property
Property Let RollZoom() As Boolean
End Property

Property Get Rows() As Range
End Property

Property Get RTD() As RTD
End Property

Property Get ScreenUpdating() As Boolean
End Property
Property Let ScreenUpdating() As Boolean
End Property

Property Get Selection() As Object
End Property

Property Get Sheets() As Sheets
End Property

Property Get SheetsInNewWorkbook() As Long
End Property
Property Let SheetsInNewWorkbook() As Long
End Property

Property Get ShowChartTipNames() As Long
End Property
Property Let ShowChartTipNames() As Long
End Property

Property Get ShowChartTipValues() As Boolean
End Property
Property Let ShowChartTipValues() As Boolean
End Property

Property Get ShowDevTools() As Boolean
End Property
Property Let ShowDevTools() As Boolean
End Property

Property Get ShowMenuFloaties() As Boolean
End Property
Property Let ShowMenuFloaties() As Boolean
End Property

Property Get ShowQuickAnalysis() As Boolean
End Property
Property Let ShowQuickAnalysis() As Boolean
End Property

Property Get ShowSelectionFloaties() As Boolean
End Property
Property Let ShowSelectionFloaties() As Boolean
End Property

Property Get ShowStartupDialog() As Boolean
End Property
Property Let ShowStartupDialog() As Boolean
End Property

Property Get ShowToolTips() As Boolean
End Property
Property Let ShowToolTips() As Boolean
End Property

Property Get SmartArtColors() As SmartArtColors
End Property

Property Get SmartArtLayouts() As SmartArtLayouts
End Property

Property Get SmartArtQuickStyles() As SmartArtQuickStyles
End Property

Property Get Speech() As Speech
End Property

Property Get SpellingOptions() As SpellingOptions
End Property

Property Get StandardFont() As String
End Property
Property Let StandardFont() As String
End Property

Property Get StandardFontSize() As Double
End Property
Property Let StandardFontSize() As Double
End Property

Property Get StartupPath() As String
End Property

Property Get StatusBar() As Variant
End Property
Property Let StatusBar() As Variant
End Property

Property Get TemplatesPath() As String
End Property

Property Get ThisCell() As Range
End Property

Property Get ThisWorkbook() As Workbook
End Property

Property Get ThousandsSeparator() As String
End Property
Property Let ThousandsSeparator() As String
End Property

Property Get Top() As Double
End Property
Property Let Top() As Double
End Property

Property Get TransitionMenuKey() As String
End Property
Property Let TransitionMenuKey() As String
End Property

Property Get TransitionMenuKeyAction() As Long
End Property
Property Let TransitionMenuKeyAction() As Long
End Property

Property Get TransitionNavigKeys() As Boolean
End Property
Property Let TransitionNavigKeys() As Boolean
End Property

Property Get UsableHeight() As Double
End Property

Property Get UsableWidth() As Double
End Property

Property Get UseClusterConnector() As Boolean
End Property
Property Let UseClusterConnector() As Boolean
End Property

Property Get UsedObjects() As UsedObjects
End Property

Property Get UserControl() As Boolean
End Property
Property Let UserControl() As Boolean
End Property

Property Get UserLibraryPath() As String
End Property

Property Get UserName() As String
End Property
Property Let UserName() As String
End Property

Property Get UseSystemSeparators() As Boolean
End Property
Property Let UseSystemSeparators() As Boolean
End Property

Property Get Value() As String
End Property

Property Get VBE() As VBE
End Property

Property Get Version() As String
End Property

Property Get Visible() As Boolean
End Property
Property Let Visible() As Boolean
End Property

Property Get WarnOnFunctionNameConflict() As Boolean
End Property
Property Let WarnOnFunctionNameConflict() As Boolean
End Property

Property Get Watches() As Watches
End Property

Property Get Width() As Double
End Property
Property Let Width() As Double
End Property

Property Get Windows() As Windows
End Property

Property Get WindowsForPens() As Boolean
End Property

Property Get WindowState() As XlWindowState
End Property
Property Let WindowState() As XlWindowState
End Property

Property Get Workbooks() As Workbooks
End Property

Property Get WorksheetFunction() As WorksheetFunction
End Property

Property Get Worksheets() As Worksheets
End Property

Sub ActivateMicrosoftApp(Index As XlMSApplication)
End Sub

Sub AddCustomList(ListArray, Optional ByRow)
End Sub

Sub Calculate()
End Sub

Sub CalculateFull()
End Sub

Sub CalculateFullRebuild()
End Sub

Sub CalculateUntilAsyncQueriesDone()
End Sub

Function CentimetersToPoints(Centimeters As Double) As Double
End Function

Sub CheckAbort(Optional KeepAbort)
End Sub

Function CheckSpelling(Word As String, Optional CustomDictionary, Optional IgnoreUppercase) As Boolean
End Function

Function ConvertFormula(Formula, FromReferenceStyle As XlReferenceStyle, Optional ToReferenceStyle, Optional ToAbsolute, Optional RelativeTo)
End Function

Sub DDEExecute(Channel As Long, String As String)
End Sub

Function DDEInitiate(App As String, Topic As String) As Long
End Function

Sub DDEPoke(Channel As Long, Item, Data)
End Sub

Function DDERequest(Channel As Long, Item As String)
End Function

Sub DDETerminate(Channel As Long)
End Sub

Sub DeleteCustomList(ListNum As Long)
End Sub

Sub DisplayXMLSourcePane(Optional XmlMap)
End Sub

Sub DoubleClick()
End Sub

Function Evaluate(Name)
End Function

Function ExecuteExcel4Macro(String As String)
End Function

Function FindFile() As Boolean
End Function

Function GetCustomListContents(ListNum As Long)
End Function

Function GetCustomListNum(ListArray) As Long
End Function

Function GetOpenFilename(Optional FileFilter, Optional FilterIndex, Optional Title, Optional ButtonText, Optional MultiSelect)
End Function

Function GetPhonetic(Optional Text) As String
End Function

Function GetSaveAsFilename(Optional InitialFilename, Optional FileFilter, Optional FilterIndex, Optional Title, Optional ButtonText)
End Function

Sub Goto(Optional Reference, Optional Scroll)
End Sub

Sub Help(Optional HelpFile, Optional HelpContextID)
End Sub

Function InchesToPoints(Inches As Double) As Double
End Function

Function InputBox(Prompt As String, Optional Title, Optional Default, Optional Left, Optional Top, Optional HelpFile, Optional HelpContextID, Optional Type)
End Function

Function Intersect(Arg1 As Range, Arg2 As Range, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Range
End Function

Sub MacroOptions(Optional Macro, Optional Description, Optional HasMenu, Optional MenuText, Optional HasShortcutKey, Optional ShortcutKey, Optional Category, Optional StatusBar, Optional HelpContextID, Optional HelpFile, Optional ArgumentDescriptions)
End Sub

Sub MailLogoff()
End Sub

Sub MailLogon(Optional Name, Optional Password, Optional DownloadNewMail)
End Sub

Function NextLetter() As Workbook
End Function

Sub OnKey(Key As String, Optional Procedure)
End Sub

Sub OnRepeat(Text As String, Procedure As String)
End Sub

Sub OnTime(EarliestTime, Procedure As String, Optional LatestTime, Optional Schedule)
End Sub

Sub OnUndo(Text As String, Procedure As String)
End Sub

Sub Quit()
End Sub

Sub RecordMacro(Optional BasicCode, Optional XlmCode)
End Sub

Function RegisterXLL(Filename As String) As Boolean
End Function

Sub Repeat()
End Sub

Function Run(Optional Macro, Optional Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30)
End Function

Sub SendKeys(Keys, Optional Wait)
End Sub

Function SharePointVersion(bstrUrl As String) As Long
End Function

Sub Undo()
End Sub

Function Union(Arg1 As Range, Arg2 As Range, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Range
End Function

Sub Volatile(Optional Volatile)
End Sub

Function Wait(Time) As Boolean
End Function