'@Interface

Property Get Application() As Application
End Property

Property Get Count() As Long
End Property

Property Get Creator() As XlCreator
End Property

Property Get HPageBreaks() As HPageBreaks
End Property

Property Get Item(Index) As Object

Property Get Parent() As Object
End Property

Property Get Visible() As Variant
End Property
Property Let Visible() As Variant
End Property

Property Get VPageBreaks() As VPageBreaks
End Property

Function Add2(Optional Before, Optional After, Optional Count, Optional NewLayout) As Chart
End Function

Sub Copy(Optional Before, Optional After)
End Sub

Sub Delete()
End Sub

Sub Move(Optional Before, Optional After)
End Sub

Sub PrintOut(Optional From, Optional To, Optional Copies, Optional Preview, Optional ActivePrinter, Optional PrintToFile, Optional Collate, Optional PrToFileName)
End Sub

Sub PrintPreview(Optional EnableChanges)
End Sub

Sub Select(Optional Replace)
End Sub