'@Interface

Enum XlPasteType
    xlPateAll = -4104
    xlPasteAllExceptBorders = 7
    xlPasteAllMergingConditionalFormats = 14
    xlPasteAllUsingSourceTheme = 13
    xlPasteColumnWidths = 8
    xlPasteComments = -4144
    xlPasteFormats = -4122
    xlPasteFormulas = -4123
    xlPasteFormulasAndNumberFormats = 11
    xlPasteValidation = 6
    xlPasteValues = -4163
    xlPasteValuesAndNumberFormats = 12
End Enum