'@Interface

Function Add(Optional SourceType As XlListObjectSourceType = xlSrcRange, Optional Source, Optional LinkSource, Optional XlListObjectHasHeaders As XlYesNoGuess = xlGuess, Optional Destination, Optional TableStyleName) As ListObject
End Function

Property Get Application() As Application
End Property

Property Get Count() As Long
End Property

Property Get Creator() As XlCreator
End Property

Property Get Item()(Index) As ListObject
End Property

Property Get Parent() As Object
End Property