'@Interface

Property Get Active() As Boolean
End Property

Property Get AlternativeText() As String
End Property
Property Let AlternativeText() As String
End Property

Property Get Application() As Application
End Property

Property Get AutoFilter() As AutoFilter
End Property

Property Get Comment() As String
End Property
Property Let Comment() As String
End Property

Property Get Creator() As XlCreator
End Property

Property Get DataBodyRange() As Range
End Property

Sub Delete()
End Sub

Property Get DisplayName() As String
End Property
Property Let DisplayName() As String
End Property

Property Get DisplayRightToLeft() As Boolean
End Property

Sub ExportToVisio()
End Sub

Property Get HeaderRowRange() As Range
End Property

Property Get InsertRowRange() As Range
End Property

Property Get ListColumns() As ListColumns
End Property

Property Get ListRows() As ListRows
End Property

Property Get Name() As String
End Property
Property Let Name() As String
End Property

Property Get Parent() As Object
End Property

Function Publish(Target, LinkSource As Boolean) As String
End Function

Property Get QueryTable() As QueryTable
End Property

Property Get Range() As Range
End Property

Sub Refresh()
End Sub

Sub Resize(Range As Range)
End Sub

Property Get SharePointURL() As String
End Property

Property Get ShowAutoFilter() As Boolean
End Property
Property Let ShowAutoFilter() As Boolean
End Property

Property Get ShowAutoFilterDropDown() As Boolean
End Property
Property Let ShowAutoFilterDropDown() As Boolean
End Property

Property Get ShowHeaders() As Boolean
End Property
Property Let ShowHeaders() As Boolean
End Property

Property Get ShowTableStyleColumnStripes() As Boolean
End Property
Property Let ShowTableStyleColumnStripes() As Boolean
End Property

Property Get ShowTableStyleFirstColumn() As Boolean
End Property
Property Let ShowTableStyleFirstColumn() As Boolean
End Property

Property Get ShowTableStyleLastColumn() As Boolean
End Property
Property Let ShowTableStyleLastColumn() As Boolean
End Property

Property Get ShowTableStyleRowStripes() As Boolean
End Property
Property Let ShowTableStyleRowStripes() As Boolean
End Property

Property Get ShowTotals() As Boolean
End Property
Property Let ShowTotals() As Boolean
End Property

Property Get Slicers() As Slicers
End Property

Property Get Sort() As Sort
End Property

Property Get SourceType() As XlListObjectSourceType
End Property

Property Get Summary() As String
End Property
Property Let Summary() As String
End Property

Property Get TableObject() As TableObject
End Property

Property Get TableStyle() As Variant
End Property
Property Let TableStyle() As Variant
End Property

Property Get TotalsRowRange() As Range
End Property

Sub Unlink()
End Sub

Sub Unlist()
End Sub

Property Get XmlMap() As XmlMap
End Property