Property Get Application() As Application
End Property

Property Get Count() As Long
End Property

Property Get Creator() As XlCreator
End Property

Property Get Parent() As Object
End Property

Function Add(Optional Name, Optional RefersTo, Optional Visible, Optional MacroType, Optional ShortcutKey, Optional Category, Optional NameLocal, Optional RefersToLocal, Optional CategoryLocal, Optional RefersToR1C1, Optional RefersToR1C1Local) As Name
End Function

Function Item(Optional Index, Optional IndexLocal, Optional RefersTo) As Name
End Function