Property Get Application() As Application
End Property

Property Get Category() As String
End Property
Property Let Category() As String
End Property

Property Get CategoryLocal() As String
End Property
Property Let CategoryLocal() As String
End Property

Property Get Comment() As String
End Property
Property Let Comment() As String
End Property

Property Get Creator() As XlCreator
End Property

Property Get Index() As Long
End Property

Property Get MacroType() As XlXLMMacroType
End Property
Property Let MacroType() As XlXLMMacroType
End Property

Property Get Name() As String
End Property
Property Let Name() As String
End Property

Property Get NameLocal() As String
End Property
Property Let NameLocal() As String
End Property

Property Get Parent() As Object
End Property

Property Get RefersTo() As Variant
End Property
Property Let RefersTo() As Variant
End Property

Property Get RefersToLocal() As Variant
End Property
Property Let RefersToLocal() As Variant
End Property

Property Get RefersToR1C1() As Variant
End Property
Property Let RefersToR1C1() As Variant
End Property

Property Get RefersToR1C1Local() As Variant
End Property
Property Let RefersToR1C1Local() As Variant
End Property

Property Get RefersToRange() As Range
End Property

Property Get ShortcutKey() As String
End Property
Property Let ShortcutKey() As String
End Property

Property Get ValidWorkbookParameter() As Boolean
End Property

Property Get Value() As String
End Property
Property Let Value() As String
End Property

Property Get Visible() As Boolean
End Property
Property Let Visible() As Boolean
End Property

Property Get WorkbookParameter() As Boolean
End Property
Property Let WorkbookParameter() As Boolean
End Property

Sub Delete()
End Sub