'@Interface

Function Activate()
End Function

Function ActivateNext()
End Function

Function ActivatePrevious()
End Function

Property Get ActiveCell() As Range
End Property

Property Get ActiveChart() As Chart
End Property

Property Get ActivePane() As Pane
End Property

Property Get ActiveSheet() As Object
End Property

Property Get ActiveSheetView() As Object
End Property

Property Get Application() As Application
End Property

Property Get AutoFilterDateGrouping() As Boolean
End Property
Property Let AutoFilterDateGrouping() As Boolean
End Property

Property Get Caption() As Variant
End Property
Property Let Caption() As Variant
End Property

Function Close(Optional SaveChanges, Optional Filename, Optional RouteWorkbook) As Boolean
End Function

Property Get Creator() As XlCreator
End Property

Property Get DisplayFormulas() As Boolean
End Property
Property Let DisplayFormulas() As Boolean
End Property

Property Get DisplayGridlines() As Boolean
End Property
Property Let DisplayGridlines() As Boolean
End Property

Property Get DisplayHeadings() As Boolean
End Property
Property Let DisplayHeadings() As Boolean
End Property

Property Get DisplayHorizontalScrollBar() As Boolean
End Property
Property Let DisplayHorizontalScrollBar() As Boolean
End Property

Property Get DisplayOutline() As Boolean
End Property
Property Let DisplayOutline() As Boolean
End Property

Property Get DisplayRightToLeft() As Boolean
End Property
Property Let DisplayRightToLeft() As Boolean
End Property

Property Get DisplayRuler() As Boolean
End Property
Property Let DisplayRuler() As Boolean
End Property

Property Get DisplayVerticalScrollBar() As Boolean
End Property
Property Let DisplayVerticalScrollBar() As Boolean
End Property

Property Get DisplayWhitespace() As Boolean
End Property
Property Let DisplayWhitespace() As Boolean
End Property

Property Get DisplayWorkbookTabs() As Boolean
End Property
Property Let DisplayWorkbookTabs() As Boolean
End Property

Property Get DisplayZeros() As Boolean
End Property
Property Let DisplayZeros() As Boolean
End Property

Property Get EnableResize() As Boolean
End Property
Property Let EnableResize() As Boolean
End Property

Property Get FreezePanes() As Boolean
End Property
Property Let FreezePanes() As Boolean
End Property

Property Get GridlineColor() As Long
End Property
Property Let GridlineColor() As Long
End Property

Property Get GridlineColorIndex() As XlColorIndex
End Property
Property Let GridlineColorIndex() As XlColorIndex
End Property

Property Get Height() As Double
End Property
Property Let Height() As Double
End Property

Property Get Hwnd() As Long
End Property

Property Get Index() As Long
End Property

Function LargeScroll(Optional Down, Optional Up, Optional ToRight, Optional ToLeft)
End Function

Property Get Left() As Double
End Property
Property Let Left() As Double
End Property

Function NewWindow() As Window
End Function

Property Get OnWindow() As String
End Property
Property Let OnWindow() As String
End Property

Property Get Panes() As Panes
End Property

Property Get Parent() As Object
End Property

Function PointsToScreenPixelsX(Points As Long) As Long
End Function

Function PointsToScreenPixelsY(Points As Long) As Long
End Function

Function PrintOut(Optional From, Optional To, Optional Copies, Optional Preview, Optional ActivePrinter, Optional PrintToFile, Optional Collate, Optional PrToFileName)
End Function

Function PrintPreview(Optional EnableChanges)
End Function

Function RangeFromPoint(x As Long, y As Long) As Object
End Function

Property Get RangeSelection() As Range
End Property

Property Get ScrollColumn() As Long
End Property
Property Let ScrollColumn() As Long
End Property

Sub ScrollIntoView(Left As Long, Top As Long, Width As Long, Height As Long, Optional Start)

Property Get ScrollRow() As Long
End Property
Property Let ScrollRow() As Long
End Property

Function ScrollWorkbookTabs(Optional Sheets, Optional Position)
End Function

Property Get SelectedSheets() As Sheets
End Property

Property Get Selection() As Object
End Property

Property Get SheetViews() As SheetViews
End Property

Function SmallScroll(Optional Down, Optional Up, Optional ToRight, Optional ToLeft)
End Function

Property Get Split() As Boolean
End Property
Property Let Split() As Boolean
End Property

Property Get SplitColumn() As Long
End Property
Property Let SplitColumn() As Long
End Property

Property Get SplitHorizontal() As Double
End Property
Property Let SplitHorizontal() As Double
End Property

Property Get SplitRow() As Long
End Property
Property Let SplitRow() As Long
End Property

Property Get SplitVertical() As Double
End Property
Property Let SplitVertical() As Double
End Property

Property Get TabRatio() As Double
End Property
Property Let TabRatio() As Double
End Property

Property Get Top() As Double
End Property
Property Let Top() As Double
End Property

Property Get Type() As XlWindowType
End Property

Property Get UsableHeight() As Double
End Property

Property Get UsableWidth() As Double
End Property

Property Get View() As XlWindowView
End Property
Property Let View() As XlWindowView
End Property

Property Get Visible() As Boolean
End Property
Property Let Visible() As Boolean
End Property

Property Get VisibleRange() As Range
End Property

Property Get Width() As Double
End Property

Property Get WindowNumber() As Long
End Property

Property Get WindowState() As XlWindowState
End Property
Property Let WindowState() As XlWindowState
End Property

Property Get Zoom() As Variant
End Property
Property Let Zoom() As Variant
End Property