'@Interface

Property Get Application() As Application
End Property

Property Get Count() As Long
End Property

Property Get Creator() As XlCreator
End Property

Property Get Item(Index) As Window

Property Get Parent() As Object
End Property

Property Get SyncScrollingSideBySide() As Boolean
End Property
Property Let SyncScrollingSideBySide() As Boolean
End Property

Function Arrange(Optional ArrangeStyle As XlArrangeStyle = xlArrangeStyleTiled, Optional ActiveWorkbook, Optional SyncHorizontal, Optional SyncVertical)
End Function

Function BreakSideBySide() As Boolean
End Function

Function CompareSideBySideWith(WindowName) As Boolean
End Function

Sub ResetPositionsSideBySide()
End Sub