'@Interface

Property Get Application() As Application
End Property

Property Get Creator() As XlCreator
End Property

Property Get Parent() As Object
End Property

Function AccrInt(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Optional Arg7) As Double
End Function

Function AccrIntM(Arg1, Arg2, Arg3, Arg4, Optional Arg5) As Double
End Function

Function Acos(Arg1 As Double) As Double
End Function

Function Acosh(Arg1 As Double) As Double
End Function

Function Acot(Arg1 As Double) As Double
End Function

Function Acoth(Arg1 As Double) As Double
End Function

Function Aggregate(Arg1 As Double, Arg2 As Double, Arg3 As Range, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function AmorDegrc(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Optional Arg7) As Double
End Function

Function AmorLinc(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Optional Arg7) As Double
End Function

Function And(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Boolean
End Function

Function Arabic(Arg1 As String) As Double
End Function

Function Asc(Arg1 As String) As String
End Function

Function Asc(Arg1 As String) As String
End Function

Function Asinh(Arg1 As Double) As Double
End Function

Function Atan2(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Atanh(Arg1 As Double) As Double
End Function

Function AveDev(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Average(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function AverageIf(Arg1 As Range, Arg2, Optional Arg3) As Double
End Function

Function AverageIfs(Arg1 As Range, Arg2 As Range, Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29) As Double
End Function

Function BahtText(Arg1 As Double) As String
End Function

Function Base(Arg1 As Double, Arg2 As Double, Optional Arg3) As String
End Function

Function BesselI(Arg1, Arg2) As Double
End Function

Function BesselJ(Arg1, Arg2) As Double
End Function

Function BesselK(Arg1, Arg2) As Double
End Function

Function BesselY(Arg1, Arg2) As Double
End Function

Function Beta_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean, Optional Arg5, Optional Arg6) As Double
End Function

Function Beta_Inv(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5) As Double
End Function

Function BetaDist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5) As Double
End Function

Function BetaInv(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5) As Double
End Function

Function Bin2Dec(Arg1) As String
End Function

Function Bin2Hex(Arg1, Optional Arg2) As String
End Function

Function Bin2Oct(Arg1, Optional Arg2) As String
End Function

Function Binom_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function Binom_Dist_Range(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4) As Double
End Function

Function Binom_Inv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function BinomDist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function Bitand(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Bitlshift(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Bitor(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Bitrshift(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Bitxor(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Ceiling(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Ceiling_Math(Arg1 As Double, Optional Arg2, Optional Arg3) As Double
End Function

Function Ceiling_Precise(Arg1 As Double, Optional Arg2) As Double
End Function

Function ChiDist(Arg1 As Double, Arg2 As Double) As Double
End Function

Function ChiInv(Arg1 As Double, Arg2 As Double) As Double
End Function

Function ChiSq_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Boolean) As Double
End Function

Function ChiSq_Dist_RT(Arg1 As Double, Arg2 As Double) As Double
End Function

Function ChiSq_Inv(Arg1 As Double, Arg2 As Double) As Double
End Function

Function ChiSq_Inv_RT(Arg1 As Double, Arg2 As Double) As Double
End Function

Function ChiSq_Test(Arg1, Arg2) As Double
End Function

Function ChiTest(Arg1, Arg2) As Double
End Function

Function Choose(Arg1, Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30)
End Function

Function Clean(Arg1 As String) As String
End Function

Function Combin(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Combina(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Complex(Arg1, Arg2, Optional Arg3) As String
End Function

Function Confidence(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Confidence_Norm(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Confidence_T(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Convert(Arg1, Arg2, Arg3) As Double
End Function

Function Correl(Arg1, Arg2) As Double
End Function

Function Cosh(Arg1 As Double) As Double
End Function

Function Cot(Arg1 As Double) As Double
End Function

Function Coth(Arg1 As Double) As Double
End Function

Function Count(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function CountA(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function CountBlank(Arg1 As Range) As Double
End Function

Function CountIf(Arg1 As Range, Arg2) As Double
End Function

Function CountIfs(Arg1 As Range, Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function CoupDayBs(Arg1, Arg2, Arg3, Optional Arg4) As Double
End Function

Function CoupDays(Arg1, Arg2, Arg3, Optional Arg4) As Double
End Function

Function CoupDaysNc(Arg1, Arg2, Arg3, Optional Arg4) As Double
End Function

Function CoupNcd(Arg1, Arg2, Arg3, Optional Arg4) As Double
End Function

Function CoupNum(Arg1, Arg2, Arg3, Optional Arg4) As Double
End Function

Function CoupPcd(Arg1, Arg2, Arg3, Optional Arg4) As Double
End Function

Function Covar(Arg1, Arg2) As Double
End Function

Function Covariance_P(Arg1, Arg2) As Double
End Function

Function Covariance_S(Arg1, Arg2) As Double
End Function

Function CritBinom(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Csc(Arg1 As Double) As Double
End Function

Function Csch(Arg1 As Double) As Double
End Function

Function CumIPmt(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6) As Double
End Function

Function CumPrinc(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6) As Double
End Function

Function DAverage(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function Days(Arg1, Arg2) As Double
End Function

Function Days360(Arg1, Arg2, Optional Arg3) As Double
End Function

Function Db(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double, Optional Arg5) As Double
End Function

Function Dbcs(Arg1 As String) As String
End Function

Function DCount(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function DCountA(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function Ddb(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double, Optional Arg5) As Double
End Function

Function Dec2Bin(Arg1, Optional Arg2) As String
End Function

Function Dec2Hex(Arg1, Optional Arg2) As String
End Function

Function Dec2Oct(Arg1, Optional Arg2) As String
End Function

Function Decimal(Arg1 As String, Arg2 As Double) As Double
End Function

Function Degrees(Arg1 As Double) As Double
End Function

Function Delta(Arg1, Optional Arg2) As Double
End Function

Function DevSq(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function DGet(Arg1 As Range, Arg2, Arg3)
End Function

Function Disc(Arg1, Arg2, Arg3, Arg4, Optional Arg5) As Double
End Function

Function DMax(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function DMin(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function Dollar(Arg1 As Double, Optional Arg2) As String
End Function

Function DollarDe(Arg1, Arg2) As Double
End Function

Function DollarFr(Arg1, Arg2) As Double
End Function

Function DProduct(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function DStDev(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function DStDevP(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function DSum(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function Duration(Arg1, Arg2, Arg3, Arg4, Arg5, Optional Arg6) As Double
End Function

Function DVar(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function DVarP(Arg1 As Range, Arg2, Arg3) As Double
End Function

Function EDate(Arg1, Arg2) As Double
End Function

Function Effect(Arg1, Arg2) As Double
End Function

Function EncodeURL(Arg1 As String)
End Function

Function EoMonth(Arg1, Arg2) As Double
End Function

Function Erf(Arg1, Optional Arg2) As Double
End Function

Function Erf_Precise(Arg1) As Double
End Function

Function ErfC(Arg1) As Double
End Function

Function ErfC_Precise(Arg1) As Double
End Function

Function Even(Arg1 As Double) As Double
End Function

Function Expon_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Boolean) As Double
End Function

Function ExponDist(Arg1 As Double, Arg2 As Double, Arg3 As Boolean) As Double
End Function

Function F_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function F_Dist_RT(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function F_Inv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function F_Inv_RT(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function F_Test(Arg1, Arg2) As Double
End Function

Function Fact(Arg1 As Double) As Double
End Function

Function FactDouble(Arg1) As Double
End Function

Function FDist(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function FilterXML(Arg1 As String, Arg2 As String)
End Function

Function Find(Arg1 As String, Arg2 As String, Optional Arg3) As Double
End Function

Function FindB(Arg1 As String, Arg2 As String, Optional Arg3) As Double
End Function

Function FInv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Fisher(Arg1 As Double) As Double
End Function

Function FisherInv(Arg1 As Double) As Double
End Function

Function Fixed(Arg1 As Double, Optional Arg2, Optional Arg3) As String
End Function

Function Floor(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Floor_Math(Arg1 As Double, Optional Arg2, Optional Arg3) As Double
End Function

Function Floor_Precise(Arg1 As Double, Optional Arg2) As Double
End Function

Function Forecast_ETS(Arg1 As Double, Arg2, Arg3, Optional Arg4, Optional Arg5, Optional Arg6) As Double
End Function

Function Forecast_ETS_ConfInt(Arg1 As Double, Arg2, Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7) As Double
End Function

Function Forecast_ETS_Seasonality(Arg1, Arg2, Optional Arg3, Optional Arg4) As Double
End Function

Function Forecast_ETS_STAT(Arg1, Arg2, Arg3 As Double, Optional Arg4, Optional Arg5, Optional Arg6) As Double
End Function

Function Forecast_Linear(Arg1 As Double, Arg2, Arg3) As Double
End Function

Function Frequency(Arg1, Arg2)
End Function

Function FTest(Arg1, Arg2) As Double
End Function

Function Fv(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5) As Double
End Function

Function FVSchedule(Arg1, Arg2) As Double
End Function

Function Gamma(Arg1 As Double) As Double
End Function

Function Gamma_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function Gamma_Inv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function GammaDist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function GammaInv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function GammaLn(Arg1 As Double) As Double
End Function

Function GammaLn_Precise(Arg1 As Double) As Double
End Function

Function Gauss(Arg1 As Double) As Double
End Function

Function Gcd(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function GeoMean(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function GeStep(Arg1, Optional Arg2) As Double
End Function

Function Growth(Arg1, Optional Arg2, Optional Arg3, Optional Arg4)
End Function

Function HarMean(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Hex2Bin(Arg1, Optional Arg2) As String
End Function

Function Hex2Dec(Arg1) As String
End Function

Function Hex2Oct(Arg1, Optional Arg2) As String
End Function

Function HLookup(Arg1, Arg2, Arg3, Optional Arg4)
End Function

Function HypGeom_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double, Arg5 As Boolean) As Double
End Function

Function HypGeomDist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double) As Double
End Function

Function IfError(Arg1, Arg2)
End Function

Function IfNa(Arg1, Arg2)
End Function

Function ImAbs(Arg1) As String
End Function

Function Imaginary(Arg1) As Double
End Function

Function ImArgument(Arg1) As String
End Function

Function ImConjugate(Arg1) As String
End Function

Function ImCos(Arg1) As String
End Function

Function ImCosh(Arg1) As String
End Function

Function ImCot(Arg1) As String
End Function

Function ImCsc(Arg1) As String
End Function

Function ImCsch(Arg1) As String
End Function

Function ImDiv(Arg1, Arg2) As String
End Function

Function ImExp(Arg1) As String
End Function

Function ImLn(Arg1) As String
End Function

Function ImLog10(Arg1) As String
End Function

Function ImLog2(Arg1) As String
End Function

Function ImPower(Arg1, Arg2) As String
End Function

Function ImProduct(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As String
End Function

Function ImReal(Arg1) As Double
End Function

Function ImSec(Arg1) As String
End Function

Function ImSech(Arg1) As String
End Function

Function ImSin(Arg1) As String
End Function

Function ImSinh(Arg1) As String
End Function

Function ImSqrt(Arg1) As String
End Function

Function ImSub(Arg1, Arg2) As String
End Function

Function ImSum(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As String
End Function

Function ImTan(Arg1) As String
End Function

Function Index(Arg1, Arg2 As Double, Optional Arg3, Optional Arg4)
End Function

Function Intercept(Arg1, Arg2) As Double
End Function

Function IntRate(Arg1, Arg2, Arg3, Arg4, Optional Arg5) As Double
End Function

Function Ipmt(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double, Optional Arg5, Optional Arg6) As Double
End Function

Function Irr(Arg1, Optional Arg2) As Double
End Function

Function IsErr(Arg1) As Boolean
End Function

Function IsError(Arg1) As Boolean
End Function

Function IsEven(Arg1) As Boolean
End Function

Function IsFormula(Arg1 As Range) As Boolean
End Function

Function IsLogical(Arg1) As Boolean
End Function

Function IsNA(Arg1) As Boolean
End Function

Function IsNonText(Arg1) As Boolean
End Function

Function IsNumber(Arg1) As Boolean
End Function

Function ISO_Ceiling(Arg1 As Double, Optional Arg2) As Double
End Function

Function IsOdd(Arg1) As Boolean
End Function

Function IsoWeekNum(Arg1 As Double, Optional Arg2) As Double
End Function

Function Ispmt(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double) As Double
End Function

Function IsText(Arg1) As Boolean
End Function

Function Kurt(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Large(Arg1, Arg2 As Double) As Double
End Function

Function Lcm(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function LinEst(Arg1, Optional Arg2, Optional Arg3, Optional Arg4)
End Function

Function Ln(Arg1 As Double) As Double
End Function

Function Log(Arg1 As Double, Optional Arg2) As Double
End Function

Function Log10(Arg1 As Double) As Double
End Function

Function LogEst(Arg1, Optional Arg2, Optional Arg3, Optional Arg4)
End Function

Function LogInv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function LogNorm_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function LogNorm_Inv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function LogNormDist(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Lookup(Arg1, Arg2, Optional Arg3)
End Function

Function Match(Arg1, Arg2, Optional Arg3) As Double
End Function

Function Max(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function MDeterm(Arg1) As Double
End Function

Function MDuration(Arg1, Arg2, Arg3, Arg4, Arg5, Optional Arg6) As Double
End Function

Function Median(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Min(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function MInverse(Arg1)
End Function

Function MIrr(Arg1, Arg2 As Double, Arg3 As Double) As Double
End Function

Function MMult(Arg1, Arg2)
End Function

Function Mode(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Mode_Mult(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30)
End Function

Function Mode_Sngl(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function MRound(Arg1, Arg2) As Double
End Function

Function MultiNomial(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Munit(Arg1 As Double)
End Function

Function NegBinom_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function NegBinomDist(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function NetworkDays(Arg1, Arg2, Optional Arg3) As Double
End Function

Function NetworkDays_Intl(Arg1, Arg2, Optional Arg3, Optional Arg4) As Double
End Function

Function Nominal(Arg1, Arg2) As Double
End Function

Function Norm_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function Norm_Inv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Norm_S_Dist(Arg1 As Double, Arg2 As Boolean) As Double
End Function

Function Norm_S_Inv(Arg1 As Double) As Double
End Function

Function NormDist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function NormInv(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function NormSDist(Arg1 As Double) As Double
End Function

Function NormSInv(Arg1 As Double) As Double
End Function

Function NPer(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5) As Double
End Function

Function Npv(Arg1 As Double, Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function NumberValue(Arg1 As String, Arg2 As String, Arg3 As String) As Double
End Function

Function Oct2Bin(Arg1, Optional Arg2) As String
End Function

Function Oct2Dec(Arg1) As String
End Function

Function Oct2Hex(Arg1, Optional Arg2) As String
End Function

Function Odd(Arg1 As Double) As Double
End Function

Function OddFPrice(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, Arg8, Optional Arg9) As Double
End Function

Function OddFYield(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, Arg8, Optional Arg9) As Double
End Function

Function OddLPrice(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, Optional Arg8) As Double
End Function

Function OddLYield(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, Optional Arg8) As Double
End Function

Function Or(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Boolean
End Function

Function PDuration(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Pearson(Arg1, Arg2) As Double
End Function

Function Percentile(Arg1, Arg2 As Double) As Double
End Function

Function Percentile_Exc(Arg1, Arg2 As Double) As Double
End Function

Function Percentile_Inc(Arg1, Arg2 As Double) As Double
End Function

Function PercentRank(Arg1, Arg2 As Double, Optional Arg3) As Double
End Function

Function PercentRank_Exc(Arg1, Arg2 As Double, Optional Arg3) As Double
End Function

Function PercentRank_Inc(Arg1, Arg2 As Double, Optional Arg3) As Double
End Function

Function Permut(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Permutationa(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Phi(Arg1 As Double) As Double
End Function

Function Phonetic(Arg1 As Range) As String
End Function

Function Pi() As Double
End Function

Function Pmt(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5) As Double
End Function

Function Poisson(Arg1 As Double, Arg2 As Double, Arg3 As Boolean) As Double
End Function

Function Poisson_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Boolean) As Double
End Function

Function Power(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Ppmt(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double, Optional Arg5, Optional Arg6) As Double
End Function

Function Price(Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Optional Arg7) As Double
End Function

Function PriceDisc(Arg1, Arg2, Arg3, Arg4, Optional Arg5) As Double
End Function

Function PriceMat(Arg1, Arg2, Arg3, Arg4, Arg5, Optional Arg6) As Double
End Function

Function Prob(Arg1, Arg2, Arg3 As Double, Optional Arg4) As Double
End Function

Function Product(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Proper(Arg1 As String) As String
End Function

Function Pv(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5) As Double
End Function

Function Quartile(Arg1, Arg2 As Double) As Double
End Function

Function Quartile_Exc(Arg1, Arg2 As Double) As Double
End Function

Function Quartile_Inc(Arg1, Arg2 As Double) As Double
End Function

Function Quotient(Arg1, Arg2) As Double
End Function

Function Radians(Arg1 As Double) As Double
End Function

Function RandBetween(Arg1, Arg2) As Double
End Function

Function Rank(Arg1 As Double, Arg2 As Range, Optional Arg3) As Double
End Function

Function Rank_Avg(Arg1 As Double, Arg2 As Range, Optional Arg3) As Double
End Function

Function Rank_Eq(Arg1 As Double, Arg2 As Range, Optional Arg3) As Double
End Function

Function Rate(Arg1 As Double, Arg2 As Double, Arg3 As Double, Optional Arg4, Optional Arg5, Optional Arg6) As Double
End Function

Function Received(Arg1, Arg2, Arg3, Arg4, Optional Arg5) As Double
End Function

Function Replace(Arg1 As String, Arg2 As Double, Arg3 As Double, Arg4 As String) As String
End Function

Function ReplaceB(Arg1 As String, Arg2 As Double, Arg3 As Double, Arg4 As String) As String
End Function

Function Rept(Arg1 As String, Arg2 As Double) As String
End Function

Function Roman(Arg1 As Double, Optional Arg2) As String
End Function

Function Round(Arg1 As Double, Arg2 As Double) As Double
End Function

Function RoundDown(Arg1 As Double, Arg2 As Double) As Double
End Function

Function RoundUp(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Rri(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function RSq(Arg1, Arg2) As Double
End Function

Function RTD(progID, server, topic1, Optional topic2, Optional topic3, Optional topic4, Optional topic5, Optional topic6, Optional topic7, Optional topic8, Optional topic9, Optional topic10, Optional topic11, Optional topic12, Optional topic13, Optional topic14, Optional topic15, Optional topic16, Optional topic17, Optional topic18, Optional topic19, Optional topic20, Optional topic21, Optional topic22, Optional topic23, Optional topic24, Optional topic25, Optional topic26, Optional topic27, Optional topic28)
End Function

Function Search(Arg1 As String, Arg2 As String, Optional Arg3) As Double
End Function

Function SearchB(Arg1 As String, Arg2 As String, Optional Arg3) As Double
End Function

Function Sec(Arg1 As Double) As Double
End Function

Function Sech(Arg1 As Double) As Double
End Function

Function SeriesSum(Arg1, Arg2, Arg3, Arg4) As Double
End Function

Function Sinh(Arg1 As Double) As Double
End Function

Function Skew(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Skew_p(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Sln(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Slope(Arg1, Arg2) As Double
End Function

Function Small(Arg1, Arg2 As Double) As Double
End Function

Function SqrtPi(Arg1) As Double
End Function

Function Standardize(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function StDev(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function StDev_P(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function StDev_S(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function StDevP(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function StEyx(Arg1, Arg2) As Double
End Function

Function Substitute(Arg1 As String, Arg2 As String, Arg3 As String, Optional Arg4) As String
End Function

Function Subtotal(Arg1 As Double, Arg2 As Range, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Sum(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function SumIf(Arg1 As Range, Arg2, Optional Arg3) As Double
End Function

Function SumIfs(Arg1 As Range, Arg2 As Range, Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29) As Double
End Function

Function SumProduct(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function SumSq(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function SumX2MY2(Arg1, Arg2) As Double
End Function

Function SumX2PY2(Arg1, Arg2) As Double
End Function

Function SumXMY2(Arg1, Arg2) As Double
End Function

Function Syd(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double) As Double
End Function

Function T_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Boolean) As Double
End Function

Function T_Dist_2T(Arg1 As Double, Arg2 As Double) As Double
End Function

Function T_Dist_RT(Arg1 As Double, Arg2 As Double) As Double
End Function

Function T_Inv(Arg1 As Double, Arg2 As Double) As Double
End Function

Function T_Inv_2T(Arg1 As Double, Arg2 As Double) As Double
End Function

Function T_Test(Arg1, Arg2, Arg3 As Double, Arg4 As Double) As Double
End Function

Function Tanh(Arg1 As Double) As Double
End Function

Function TBillEq(Arg1, Arg2, Optional Arg3) As Double
End Function

Function TBillPrice(Arg1, Arg2, Optional Arg3) As Double
End Function

Function TBillYield(Arg1, Arg2, Optional Arg3) As Double
End Function

Function TDist(Arg1 As Double, Arg2 As Double, Arg3 As Double) As Double
End Function

Function Text(Arg1, Arg2 As String) As String
End Function

Function TInv(Arg1 As Double, Arg2 As Double) As Double
End Function

Function Transpose(Arg1)
End Function

Function Trend(Arg1, Optional Arg2, Optional Arg3, Optional Arg4)
End Function

Function Trim(Arg1 As String) As String
End Function

Function TrimMean(Arg1, Arg2 As Double) As Double
End Function

Function TTest(Arg1, Arg2, Arg3 As Double, Arg4 As Double) As Double
End Function

Function Unichar(Arg1 As Double) As String
End Function

Function Unicode(Arg1 As String) As Double
End Function

Function USDollar(Arg1 As Double, Arg2 As Double) As String
End Function

Function Var(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Var_P(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Var_S(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function VarP(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Double
End Function

Function Vdb(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Double, Arg5 As Double, Optional Arg6, Optional Arg7) As Double
End Function

Function VLookup(Arg1, Arg2, Arg3, Optional Arg4)
End Function

Function WebService(Arg1 As String)
End Function

Function Weekday(Arg1, Optional Arg2) As Double
End Function

Function WeekNum(Arg1, Optional Arg2) As Double
End Function

Function Weibull(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function Weibull_Dist(Arg1 As Double, Arg2 As Double, Arg3 As Double, Arg4 As Boolean) As Double
End Function

Function WorkDay(Arg1, Arg2, Optional Arg3) As Double
End Function

Function WorkDay_Intl(Arg1, Arg2, Optional Arg3, Optional Arg4) As Double
End Function

Function Xirr(Arg1, Arg2, Optional Arg3) As Double
End Function

Function Xnpv(Arg1, Arg2) As Double
End Function

Function Xor(Arg1, Optional Arg2, Optional Arg3, Optional Arg4, Optional Arg5, Optional Arg6, Optional Arg7, Optional Arg8, Optional Arg9, Optional Arg10, Optional Arg11, Optional Arg12, Optional Arg13, Optional Arg14, Optional Arg15, Optional Arg16, Optional Arg17, Optional Arg18, Optional Arg19, Optional Arg20, Optional Arg21, Optional Arg22, Optional Arg23, Optional Arg24, Optional Arg25, Optional Arg26, Optional Arg27, Optional Arg28, Optional Arg29, Optional Arg30) As Boolean
End Function

Function YearFrac(Arg1, Arg2, Optional Arg3) As Double
End Function

Function YieldDisc(Arg1, Arg2, Arg3, Arg4, Optional Arg5) As Double
End Function

Function YieldMat(Arg1, Arg2, Arg3, Arg4, Arg5, Optional Arg6) As Double
End Function

Function Z_Test(Arg1, Arg2 As Double, Optional Arg3) As Double
End Function

Function ZTest(Arg1, Arg2 As Double, Optional Arg3) As Double
End Function