'@Interface

Function Add(Optional Template) As Workbook
End Function

Property Get Application() As Application
End Property

Function CanCheckOut(Filename As String) As Boolean
End Function

Sub CheckOut(Filename As String)
End Sub

Sub Close()
End Sub

Property Get Count() As Long
End Property

Property Get Creator() As XlCreator
End Property

Property Get Item(Index) As Workbook
End Property

Function Open(Filename As String, Optional UpdateLinks, Optional ReadOnly, Optional Format, Optional Password, Optional WriteResPassword, Optional IgnoreReadOnlyRecommended, Optional Origin, Optional Delimiter, Optional Editable, Optional Notify, Optional Converter, Optional AddToMru, Optional Local, Optional CorruptLoad) As Workbook
End Function

Function OpenDatabase(Filename As String, Optional CommandText, Optional CommandType, Optional BackgroundQuery, Optional ImportDataAs) As Workbook
End Function

Sub OpenText(Filename As String, Optional Origin, Optional StartRow, Optional DataType, Optional TextQualifier As XlTextQualifier = xlTextQualifierDoubleQuote, Optional ConsecutiveDelimiter, Optional Tab, Optional Semicolon, Optional Comma, Optional Space, Optional Other, Optional OtherChar, Optional FieldInfo, Optional TextVisualLayout, Optional DecimalSeparator, Optional ThousandsSeparator, Optional TrailingMinusNumbers, Optional Local)
End Sub

Function OpenXML(Filename As String, Optional Stylesheets, Optional LoadOption) As Workbook
End Function

Property Get Parent() As Application
End Property