Const vbBack = ""
Const vbCr = "
"
Const vbCrLf = "
"
Const vbFormFeed = ""
Const vbLf = "
"
Const vbNewLine = "
"
Const vbNullChar = ""
Const vbNullString = ""
Const vbObjectError = -2147221504
Const vbTab = "	"
Const vbVerticalTab = ""