'@Interface

Sub Clear()
End Sub

Property Get Description() As String
End Property
Property Let Description()
End Property

Property Get HelpContext() As Long
End Property
Property Let HelpContext()
End Property

Property Get HelpFile() As String
End Property
Property Let HelpFile()
End Property

Property Get LastDllError() As Long
End Property

Property Get Number() As Long
End Property
Property Let Number()
End Property

Sub Raise(Number As Long, Optional Source, Optional Description, Optional HelpFile, Optional HelpContext)
End Sub

Property Get Source() As String
End Property
Property Let Source()
End Property