'@Interface

Property Get CompareMode() As CompareMethod
End Property
Property Let CompareMode() As CompareMethod
End Property

Property Get Count() As Long
End Property

Property Get Item(Key)
End Property
Property Let Item(Key)
End Property

Property Get Key(Key)
End Property
Property Let Key(Key)
End Property

Sub Add(Key, Item)
End Sub 

Function Exists(Key) As Boolean
End Function

Function Keys()
End Function

Sub Remove(Key)
End Sub 

Sub RemoveAll()
End Sub 