'@Interface

Property Get Global() As Boolean
End Property
Property Let Global() As Boolean
End Property

Property Get IgnoreCase() As Boolean
End Property
Property Let IgnoreCase() As Boolean
End Property

Property Get Multiline() As Boolean
End Property
Property Let Multiline() As Boolean
End Property

Property Get Pattern() As String
End Property
Property Let Pattern() As String
End Property

Function Execute(sourceString As String) As Object
End Function

Function Replace(sourceString As String, replaceVar) As String
End Function

Function Test(sourceString As String) As Boolean
End Function